### ISSUE TITLE
Moved shared files to shared folder, in root dir, and symlink

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/example-applications#1]
There are numerous files that have the same content but are copied into each example dir. This is because we want all relevant files for a run to be in one directory. 

To make things more maintainable we should create a shared folder in which we keep these files and then create symlinks into each example.

**Comment by ArneTR** [comment]
Currently the mechnasim of using symlinks has the following problems:
- Docker has an unsolved bug that prevents it from using Dockerfiles that are symlinked: https://github.com/docker/compose/issues/7397

We cannot just use a symlinked compose.yml file and have the Dockerfile as a real file in the shared directory, cause this would mean we would have the "context" variable in the compose.yml file to be fixed.

If we ever want to use the shared Dockerfile in a subfolder that is deeper than the first level this directory traversal would fail.

Therefore the solution for now:
- Put a Dockerfile and compose.yml that we can reuse in the shared folder
- Put a explanaition in the README that the container should be build with the command: `docker compose -f ../shared/stress/compose.yml` build

**Comment by ArneTR** [comment]
We are using `build.sh` files in the respective folders now
