### ISSUE TITLE
Update puppeteer container with new packages

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/example-applications#15]

**Comment by ArneTR** [comment]
Look at the approach in https://github.com/green-coding-berlin/example-applications/compare/main...container-slim

**Comment by ArneTR** [comment]
Please also fix the documentation bugs in the Readme regarding docker compose run

**Comment by ArneTR** [comment]
I changed the references in the documentation. No need for you to do that from your side

**Comment by ArneTR** [comment]
I tried downloading the containers with the testing tag from Docker Hub: `docker pull greencoding/puppeteer-chrome:testing`.

The containers arrive fine and size is reduced as expected. However they cannot start:

`docker run --rm -it greencoding/puppeteer-chrome:testing` 

gives me:

`Docker build: cannot mount volume over existing file ...`

The problem is: Since you built the containers with the docker compose file and not with just the docker build client it somehow expects or has saved the bind mount information.

Since the container should be redistributable and people might not have the directory structure of your development machine this makes the container very limited in where it can be run.

The solution is to remove the build information from the `compose.yml` file and instruct the user to build via the `docker build` CLI command.

Please re-upload the containers again to Docker Hub as testing containers with the new way of building them. I will test again then.

Learning for us: Containers on Docker Hub should never have bind mounts! Neither through the `docker build` nor the `compose.yml` file.

I left the `compose.yml` file nevertheless in the folder as it is very nice for starting and testing the containers.

**Comment by djesic** [comment]
@ArneTR 
I updated the readme on how to run the images when they are built locally, and updated the Dockerfile to include the COPY of the test script as opposed to using a volume mount in the docker compose file.
Images built including these Dockerfiles have been pushed to docker hub under the `testing` tag, please try pulling and running them.
