### ISSUE TITLE
Second refactoring of container names

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/example-applications#19]
Currently we have most container and image names renamed to our new format "gcb_ ..."

However the *wordpress-offfical-data* and similar repositories still use legacy container names. Reason being, these names are used as hostnames for HTTP access or hostname based networking.

So we cannot actually use underscores in our container names.

In turn we would like to move all image names to underscore based naming (which should already be done). 
And move all container names to the SAME name as the image, only with dashes.

This must also be documented in the documentation somewhere that our example applications  follow this logic.

**Comment by djesic** [comment]
https://docs.green-coding.org/docs/measuring/containerizing-applications/
https://docs.green-coding.org/docs/contributing/example-applications-contribution/
