### ISSUE TITLE
Normalise names for docker containers

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/example-applications#2]
Currently container names are sometimes set by the build and such are not consistent. 

We need to go through all the containers and set the name in `compose.yml`

**Comment by ArneTR** [comment]
for every folder in the example-applications repository:
- Read Readme
- Try running containers with docker compose up
- Try executing usage_scenario with the green metrics tool
-> We had the issue that image names got out of sync with the names in the usage_scenario.yml
---> Therefore please update all compose.yml files to FORCE the image name expected in the usage_scenario.yml
-----> version: "2" # at the top
-----> image: EXPECTED_IMAGE_NAME # under the "services" key


do the same also with the 
- https://github.com/green-coding-berlin/simple-example-application repository 
- https://github.com/green-coding-berlin/wordpress-static repo

**Comment by ArneTR** [comment]
Please look at the pull request to merge already done work in: https://github.com/green-coding-berlin/example-applications/pull/4

**Comment by ArneTR** [comment]
Merged refactoring. Good work!
