### ISSUE TITLE
Bug / Improvement: Workflow runs in Example Applications call docker commands manually instead of using shell scripts

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/example-applications#21]
`docker compose -f ../docker/test-compose.yml down -v` is called manually.

Would it not make more sense to reuse the existing "stop-test-containers.sh" file? This one would also directly incorporate changes we make to it ... like the newly added *--remove-orphans*

**Comment by dan-mm** [comment]
the only difference between the call in the script and the one in the workflow was that the workflow used the -d detached flag, where the script does not.

I added the flag as an arguement to the script and the workflow now references the script.

this change was made both the the green-metrics-tool repo and the examples-directory repo

**Comment by ArneTR** [comment]
I see the commit in https://github.com/green-coding-berlin/example-applications/commit/22389b5b657d3393a0707e5ace4b9203b10217b7 but I do not understand why the `-d` is there ... shouldn't the `-d` rather be ported to the code in the GMT?

**Comment by ArneTR** [comment]
Looked at it and saw it in your branch in the GMT
